imports:
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/parameters.yml" }
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/services.yml" }
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/resources.yml" }

parameters:
    locastic_sylius_comparer_plugin.model.comparer.class: Locastic\SyliusComparerPlugin\Entity\Comparer
    locastic_sylius_comparer_plugin.model.comparer_product.class: Locastic\SyliusComparerPlugin\Entity\ComparerProduct


