sylius_resource:
    resources:
        locastic.comparer:  
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusComparerPlugin\Entity\Comparer
                interface: Locastic\SyliusComparerPlugin\Entity\ComparerInterface
                repository: Locastic\SyliusComparerPlugin\Repository\ComparerRepository  

        locastic.comparer_product: 
            driver: doctrine/orm
            classes:
                model: Locastic\SyliusComparerPlugin\Entity\ComparerProduct
                interface: Locastic\SyliusComparerPlugin\Entity\ComparerProductInterface
                repository: Locastic\SyliusComparerPlugin\Repository\ComparerProductRepository  