imports:
    - { resource: services/controllers.yml }
    - { resource: services/factories.yml }
    - { resource: services/validators.yml }

services:

    locastic_sylius_comparer_plugin.context.comparer_context:
        class: Locastic\SyliusComparerPlugin\Context\ComparerContext
        arguments:
            - "@security.token_storage"
            - "@locastic_sylius_comparer_plugin.custom_factory.comparer"
            - "@locastic_sylius_comparer_plugin.repository.comparer"
            - "%comparer_cookie_token%"

    locastic_sylius_comparer_plugin.utils.comparer_capacity_checker:
        class: Locastic\SyliusComparerPlugin\Utils\ComparerCapacityChecker
        arguments:
            - "%comparer_item_limit%"

    locastic.sylius_comparer_plugin.utils.comparer_token:
        class: Locastic\SyliusComparerPlugin\Utils\ComparerToken
        arguments:
            - "@sylius.random_generator"

    locastic_sylius_comparer_plugin.block.inject_style:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - "LocasticSyliusComparerPlugin::_stylesheets.html.twig"
        tags:
            -
                name: kernel.event_listener
                event: sonata.block.event.sylius.shop.layout.header
                method: onBlockEvent

    locastic.sylius_comparer_plugin.utils.message_redirect_helper:
        class: Locastic\SyliusComparerPlugin\Utils\MessageRedirectHelper
        arguments:
            - "@session.flash_bag"
            - "@router.default"
            - "@sylius.theme.translation.translator"

    locastic_sylius_comparer_plugin.factory.comparer:
        class: Sylius\Component\Resource\Factory\Factory
        arguments:
            - '%locastic_sylius_comparer_plugin.model.comparer.class%'

    locastic_sylius_comparer_plugin.factory.comparer_product:
        class: Sylius\Component\Resource\Factory\Factory
        arguments:
            - '%locastic_sylius_comparer_plugin.model.comparer_product.class%'

    locastic_sylius_comparer_plugin.custom_factory.comparer:
        class: Locastic\SyliusComparerPlugin\Factory\ComparerFactory
        decorates: locastic_sylius_comparer_plugin.factory.comparer
        arguments:
            - '@locastic_sylius_comparer_plugin.factory.comparer.inner'
            - '@sylius.factory.customer'
            - '@sylius.factory.product'
    
    locastic_sylius_comparer_plugin.custom_factory.comparer_product:
        class: Locastic\SyliusComparerPlugin\Factory\ComparerProductFactory
        decorates: locastic_sylius_comparer_plugin.factory.comparer_product
        arguments:
            - '@locastic_sylius_comparer_plugin.factory.comparer_product.inner'
            - '@locastic_sylius_comparer_plugin.repository.comparer'
            - '@sylius.repository.product'

parameters:
    comparer_item_limit: 4
    comparer_cookie_token: 'locastic_sylius_comparer'